SystemCode:
  VCO: "CRM OSB"
  VBP: "VCARE BUS POOL (Siebel Pool)"
  VBR: "VCARE Bill Return Web"
  VBS: "VCARE BUS SERVICE (Siebel Business Service Client)"
  VCC: "Contingency Care System"
  VCM: "VCARE Cable Modem Web"
  VCP: "CONVERGENT PROFILE MANAGEMENT"
  VCR: "VCARE CRM Web"
  VCS: "VCARE Schedule (Java)"
  VCV: "CVSS"
  VDC: "VCARE Discount Web"
  VES: "ESPG"
  VHS: "VCARE HI-SPEED Web"
  VHT: "VCARE HTTP SERVICE (C#.Net)"
  VIC: "ICRM"
  VIV: "IVR Dispatch"
  VNS: "NAS"
  VNT: "True Net Talk Web"
  VOG: "TOM Gateway"
  VOM: "TOM Web Application"
  VSB: "VCARE SIEBEL APPLICATION"
  VSM: "VCARE SLA Manager Web"
  VSO: "VCARE Service Order Web"
  VTP: "TAPS"
  VTS: "VCARE Tivoli Schedule"
  VUT: "VCARE Utility"
  VWS: "VCARE WEB SERVICE (True App Gateway)"
  CDB: "CRM Database"
  CIB: "CRM Inbound API"
  COB: "CRM Outbound API"
  CIG: "CRM Integration"
  CVD: "CRM Validation API"
  CJS: "CRM Job Schedule"
  IVR: "IVR"
  CRMEAI: "CRM Siebel EAI"
  OMXMB: "OMX Mobile"
ModuleCode:
  AA: "AUTHENTICATION AND AUTHORIZATION"
  AC: "ACCOUNT"
  AD: "ADDRESS"
  AJ: "ADJUSTMENT"
  AM: "ACCUMULATION"
  AP: "APPROVE CODE"
  AS: "ASSET"
  AV: "ACTIVITY"
  BK: "BLACK LIST"
  BL: "BILLING"
  BM: "BILL IMAGE"
  BN: "BONUS"
  BR: "BILL RETURN"
  CA: "CACHE"
  CD: "CREDIT NOTE"
  CF: "CONFIGURATION"
  CL: "COLLECTION"
  CN: "CAMPAIGN"
  CO: "CLOSE ORDER"
  CP: "COMPLAIN"
  CT: "CONTACT"
  DB: "DELINK BAN"
  DC: "DISCOUNT"
  DP: "DEPARTMENT"
  DV: "DIVISION"
  EC: "ERROR CODE"
  EM: "E-MAIL"
  EP: "EMPLOYEE"
  EV: "EVALUATE CREDIT CLASS"
  EW: "E-WORKFLOW"
  FF: "FRIEND AND FAMILY"
  FU: "FOLLOW UP"
  FX: "FAX"
  IC: "INBOUND CALL"
  IN: "INVENTORY"
  LB: "LINK BAN"
  LV: "LIST OF VALUE"
  MA: "MAX ALLOW"
  MI: "MOBILE ID"
  NA: "NUMBER ALLOCATION"
  NP: "NON PAPER BILL"
  NR: "NON RECEIVE BILL"
  OC: "OUTBOUND CALL"
  OD: "ORDER"
  OF: "OFFER"
  PD: "PRODUCT"
  PP: "PRICE PLAN"
  PS: "POSITION"
  PV: "PROVISIONING"
  RG: "REGISTER"
  RT: "RETENTION"
  RP: "REQUEST TO PAY"
  SB: "SEND BILL"
  SL: "SOLUTION"
  SM: "SMS"
  SR: "SERVICE REQUEST"
  TT: "TROUBLE TICKET"
  TU: "TURF"
  WA: "WEB APPLICATION"
  HT: "HOLDING TAX"
  ET: "ELECTRONIC TAX"
  DCB: "DCB"
ErrorCode:
  0: "Success|SUCCESS_CODE|A|0"
  101000: "Parameter %s is required.|REQUIRED_CODE|B|2"
  102000: "Parameter %s is invalid.|INVALID_CODE|B|2"
  103000: "Parameter %s dependent on %s.|DEPENDENCY_VALUE_CODE|B|2"
  104000: "Parameter %s is not match in %s system.|NO_MATCH_CODE|B|2"
  105000: "Parameter %s is outside allowable range %s.|OVER_RANGE_CODE|B|2"
  201000: "Data %s not found in %s system.|NOT_FOUND_CODE|A|4"
  202000: "Data %s is duplicate in %s system.|MANY_ROWS_CODE|A|4"
  203000: "Data %s is invalid in %s system.|DATA_INVALID_CODE|A|4"
  300000: "Business logic error because %s.|BUSINESS_CODE|B|3"
  300001: "Do not cancel this transaction because %s.|BUSINESS_CODE|B|3"
  300002: "Order %s is not register the non paper bill.|BUSINESS_CODE|B|3"
  300003: "Order อยู่ในสถานะที่ไม่สามารถสร้าง Order %s ได้.|BUSINESS_CODE|B|3"
  300004: "หมายเลข %s มีบริการที่มี Product Category: %s แล้ว คือ %s|BUSINESS_CODE|B|3"
  300005: "This transaction is in process on ESPG server. SPG_ID: %s State: %s|BUSINESS_CODE|B|3"
  300006: "สมัคร send bill ได้เฉพาะลูกค้า Corporate เท่านั้นครับ|BUSINESS_CODE|B|3"
  300007: "Bans have pending requests.|BUSINESS_CODE|B|3"
  300008: "The mother ban %s you are trying to link, have pending requests. Please go to cancel request of mother ban at CVSS.|BUSINESS_CODE|B|3"
  300009: "The mother ban %s No Existing Products.|BUSINESS_CODE|B|3"
  300010: "CVSS can not insert customer profile because link ban more than %s ban.|BUSINESS_CODE|B|3"
  300011: "CVSS found duplicate ban.|BUSINESS_CODE|B|3"
  300012: "CVSS can not Request IR more than number of subscriber.|BUSINESS_CODE|B|3"
  300013: "CVSS can not Request IDD more than number of subscriber.|BUSINESS_CODE|B|3"
  300014: "Number of request %s more than maximum request %s in CVSS system.|BUSINESS_CODE|B|3"
  300015: "CVSS can not can\u0E01cel this BAN %s because BAN was %s.|BUSINESS_CODE|B|3"
  300016: "CVSS mark delete BAN %s fail.|BUSINESS_CODE|B|3"
  300017: "BAN %s already deleted.|BUSINESS_CODE|B|3"
  300018: "BN is waiting to %s this future order on %s.|BUSINESS_CODE|B|3"
  300019: "Do not add this SocName: %s because over maximum instances allowed.|BUSINESS_CODE|B|3"
  300020: "Invalid individual customer|BUSINESS_CODE|B|3"
  300021: "BAN status %s is not allowed|BUSINESS_CODE|B|3"
  300022: "Delinquent flag %s is not allowed|BUSINESS_CODE|B|3"
  300023: "Account type %s is not allowed|BUSINESS_CODE|B|3"
  300024: "Credit class %s is not allowed|BUSINESS_CODE|B|3"
  300025: "3 first billing cycle is not closed|BUSINESS_CODE|B|3"
  300026: "Have to open the number for more than %s days|BUSINESS_CODE|B|3"
  300027: "The value AR Balance greater than 0|BUSINESS_CODE|B|3"
  300028: "The value AR Balance is less than equal to 0|BUSINESS_CODE|B|3"
  300029: "The value Total Obligation x 1.1 is greater than %s|BUSINESS_CODE|B|3"
  300030: "Signal can be activated %s|BUSINESS_CODE|B|3"
  300031: "Exceeding the number of privileges %s|BUSINESS_CODE|B|3"
  300032: "Source system %s is not allow|BUSINESS_CODE|B|3"
  300033: "Full Suspend than %s days is not allow|BUSINESS_CODE|B|3"
  300034: "Total Obligation must greater than credit limit|BUSINESS_CODE|B|3"
  300035: "Customer Grading %s is not allow|BUSINESS_CODE|B|3"
  300036: "Fixed Line Plus is not allow|BUSINESS_CODE|B|3"
  300037: "Asset status %s is not allow|BUSINESS_CODE|B|3"
  300038: "ServiceId in trial period is not allow|BUSINESS_CODE|B|3"
  300040: "Campaign %s expire|BUSINESS_CODE|B|4"
  300041: "Campaign %s accept by %s |BUSINESS_CODE|B|4"
  300042: "Customer have contract in Contract List|BUSINESS_CODE|B|4"
  300043: "Asset %s status not active|BUSINESS_CODE|B|4"
  300044: "Campaign %s Reject|BUSINESS_CODE|B|4"
  300045: "Can not %s %s in %s system|CAMPAIGN_DATABASE_CODE|B|4"
  300046: "ไม่สามารถทำรายการได้ เนื่องจากหมายเลขนี้ มี Soc: %s อยู่แล้ว|BUSINESS_CODE|B|4"
  310000: "The validation already failed because %s|VALIDATION_CODE|B|4"
  400000: "Application name: %s occur error because %s.|APPLICATION_CODE|S|5"
  801000: "%s database occur timeout.|DB_TIMEOUT_CODE|S|5"
  801001: "API serviceName: %s methodName: %s occur timeout.|API_TIMEOUT_CODE|S|5"
  801002: "Session variable occur timeout.|SESSION_TIMEOUT_CODE|S|5"
  802000: "Vcare database access error because %s.|VCARE_DATABASE_CODE|S|5"
  802001: "ESPG database access error because %s.|ESPG_DATABASE_CODE|S|5"
  802002: "TAP database access error because %s.|TAP_DATABASE_CODE|S|5"
  802003: "ATP database access error because %s.|ATP_DATABASE_CODE|S|5"
  802004: "NAS database access error because %s.|NAS_DATABASE_CODE|S|5"
  802005: "CVSS database access error because %s.|CVSS_DATABASE_CODE|S|5"
  802006: "ICRM database access error because %s.|ICRM_DATABASE_CODE|S|5"
  802007: "IVR database access error because %s.|IVR_DATABASE_CODE|S|5"
  802008: "CCC database access error because %s.|CCC_DATABASE_CODE|S|5"
  802009: "True Amdoc database access error because %s.|TRUE_AMDOC_DATABASE_CODE|S|5"
  802010: "MRPRD database access error because %s.|MRPRD_DATABASE_CODE|S|5"
  802011: "CDS database access error because %s.|CDS_DATABASE_CODE|S|5"
  802012: "CCBS database access error because %s.|CCBS_DATABASE_CODE|S|5"
  802013: "CRMOSB database access error because %s.|CRMOSB_DATABASE_CODE|S|5"
  802014: "CRM database access error because %s.|CRM_DATABASE_CODE|S|5"
  802015: "MID database access error because %s.|MID_DATABASE_CODE|S|5"
  803001: "Can not write file because %s.|WRITE_FILE_CODE|S|5"
  803002: "Can not read file because %s.|READ_FILE_CODE|S|5"
  803003: "Can not delete file because %s.|DELETE_FILE_CODE|S|5"
  803004: "Can not upload file because %s.|UPLOAD_FILE_CODE|S|5"
  803005: "File Name: %s not found in %s system.|FILE_NOT_FOUND_CODE|S|5"
  803006: "File Name: %s is incomplete because %s.|FILE_INCOMPLETE_CODE|S|5"
  804000: "Mail server: %s access error because %s.|MAIL_SERVER_CODE|S|5"
  900000: "Call True Amdoc API serviceName: %s methodName: %s|TRUE_AMDOC_API_CODE|S|5"
  900001: "Call TrueMove Amdoc API serviceName: %s methodName: %s|TMV_AMDOC_API_CODE|S|5"
  900002: "Call CCSS API serviceName: %s methodName: %s|CCSS_API_CODE|S|5"
  900003: "Call CFM API serviceName: %s methodName: %s|CFM_API_CODE|S|5"
  900004: "Call CIA API serviceName: %s methodName: %s|CIA_API_CODE|S|5"
  900005: "Call Metasolve API serviceName: %s methodName: %s|METASOLVE_API_CODE|S|5"
  900006: "Call Microbilling API serviceName: %s methodName: %s|MICROBILLING_API_CODE|S|5"
  900007: "Call Prepaid API serviceName: %s methodName: %s|PREPAID_API_CODE|S|5"
  900008: "Call CCR API serviceName: %s methodName: %s|CCR_API_CODE|S|5"
  900009: "Call TCC API serviceName: %s methodName: %s|TCC_API_CODE|S|5"
  900010: "Call TrueVisions API serviceName: %s methodName: %s|TVS_API_CODE|S|5"
  900011: "Call MobileNumberPort API serviceName: %s methodName: %s|MNP_API_CODE|S|5"
  900012: "Call W4 API serviceName: %s methodName: %s|W4_API_CODE|S|5"
  900013: "Call Network Operation API serviceName: %s methodName: %s|NETWORK_OPER_API_CODE|S|5"
  900014: "Call SAP API serviceName: %s methodName: %s|SAP_API_CODE|S|5"
  900015: "Call EBPP API serviceName: %s methodName: %s|EBPP_API_CODE|S|5"
  900016: "Call MCP API serviceName: %s methodName: %s|MCP_API_CODE|S|5"
  900017: "Call ListManagement API serviceName: %s methodName: %s|LIST_MANAGEMENT_API_CODE|S|5"
  900018: "Call CCBS API serviceName: %s methodName: %s|CCBS_API_CODE|S|5"
  900019: "Call CCB-INT API serviceName: %s methodName: %s|CCB-INT_API_CODE|S|5"
  900020: "Call OMX API serviceName: %s methodName: %s|OMX_API_CODE|S|5"
  900021: "Call OM API serviceName: %s methodName: %s|OM_API_CODE|S|5"
  900022: "Call QRun API serviceName: %s methodName: %s|QRUN_API_CODE|S|5"
  900023: "Call CMX API serviceName: %s methodName: %s|CMX_API_CODE|S|5"
  900024: "Call WhatUp API serviceName: %s methodName: %s|WHAT_UP_API_CODE|S|5"
  900025: "Call CRM EAI API serviceName: %s methodName: %s|CRM_EAI_API_CODE|S|5"
  900026: "Call CRM Inbound API serviceName: %s methodName: %s|CRM_INBOUND_API_CODE|S|5"
  900027: "Call CRM Outbound API serviceName: %s methodName: %s|CRM_OUTBOUND_API_CODE|S|5"
  900028: "Call CRM Validation API serviceName: %s methodName: %s|CRM_VALIDATION_API_CODE|S|5"
  900029: "Call DMC API serviceName: %s methodName: %s|DMC_API_CODE|S|5"
  900030: "Call MELON API serviceName: %s methodName: %s|MELON_API_CODE|S|5"
  900031: "Call 3CJ API serviceName: %s methodName: %s|3CJ_API_CODE|S|5"
  900032: "Call ONETRUST API serviceName: %s methodName: %s|ONETRUST_API_CODE|S|5"
  900033: "Call MVP API serviceName: %s methodName: %s|MVP_API_CODE|S|5"
  910000: "Call Vcare API serviceName: %s methodName: %s|VCARE_API_CODE|S|5"
  910001: "Call ESPG API serviceName: %s methodName: %s|ESPG_API_CODE|S|5"
  910002: "Call TAP API serviceName: %s methodName: %s|TAP_API_CODE|S|5"
  910003: "Call ATP API serviceName: %s methodName: %s|ATP_API_CODE|S|5"
  910004: "Call NAS API serviceName: %s methodName: %s|NAS_API_CODE|S|5"
  910005: "Call CVSS API serviceName: %s methodName: %s|CVSS_API_CODE|S|5"
  910006: "Call ICRM API serviceName: %s methodName: %s|ICRM_API_CODE|S|5"
  910007: "Call IVR API serviceName: %s methodName: %s|IVR_API_CODE|S|5"
  910008: "Call BUS POOL API serviceName: %s methodName: %s|BS_POOL_CODE|S|5"
  920000: "Can not connect to XML API serviceName: %s methodName: %s because %s.|XML_API_CODE|S|5"
  920001: "Can not connect to Web Service serviceName: %s methodName: %s because %s.|WS_API_CODE|S|5"
  920002: "Can not connect to EJB API serviceName: %s methodName: %s because %s.|EJB_API_CODE|S|5"
  920003: "Can not connect to REST API serviceName: %s methodName: %s because %s.|REST_API_CODE|S|5"